### ISSUE TITLE
my_help install

### ISSUE THREAD

**Issue by XiaoHanQi** [daddygongon/my_help#100]
os:windows 10 pro
shell:CMD
editor:

C:\Users\lab>export http_proxy=http://proxy.kwansei.ac.jp:8080
'export' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
-----proxy設定するとき，エラーが起きた ．
C:\Users\lab>set http_proxy=http://proxy.kwansei.ac.jp:8080
-----exportの代わりにsetを入れてインストールできた．
C:\Users\lab>gem install my_help
Fetching my_help-0.8.0.gem
Fetching gli-2.17.1.gem
Successfully installed gli-2.17.1
Successfully installed my_help-0.8.0
Parsing documentation for gli-2.17.1
Installing ri documentation for gli-2.17.1
Parsing documentation for my_help-0.8.0
Installing ri documentation for my_help-0.8.0
Done installing documentation for gli, my_help after 2 seconds
2 gems installed

C:\Users\lab>gem install thor
Fetching thor-0.20.3.gem
Successfully installed thor-0.20.3
Parsing documentation for thor-0.20.3
Installing ri documentation for thor-0.20.3
Done installing documentation for thor after 2 seconds
1 gem installed

C:\Users\lab>my_help
Commands:
  my_help delete {help_name}       # delete HELP_NAME
  my_help edit {help_name}         # edit HELP_NAME
  my_help help [COMMAND]           # Describe available commands or one speci...
  my_help list                     # list all helps, specific HELP, or item
  my_help new {help_name}          # make new HELP_NAME
  my_help search {find_char}       # search FIND_CHAR
  my_help tomo_upload {help_name}  # tomo_upload HELP_NAME

------これから，githubからmy_help ダウンロードしてインストールする．

C:\Users\lab>git clone git@github.com:daddygongon/my_help.git
Cloning into 'my_help'...
Warning: Permanently added the RSA host key for IP address '52.69.186.44' to the list of known hosts.
remote: Enumerating objects: 235, done.
remote: Counting objects: 100% (235/235), done.
remote: Compressing objects: 100% (139/139), done.
remote: Total 4121 (delta 123), reused 195 (delta 89), pack-reused 3886Receiving objects:  98% (4039/4121), 51.07 MiB |
Receiving objects: 100% (4121/4121), 52.39 MiB | 5.23 MiB/s, done.
Resolving deltas: 100% (2320/2320), done.
------インストールできた
C:\Users\lab>cd my_help
C:\Users\lab\my_help>dir
 ドライブ C のボリューム ラベルは Windows です
 ボリューム シリアル番号は B04E-30C0 です

 C:\Users\lab\my_help のディレクトリ

2019/12/11  15:57    <DIR>          .
2019/12/11  15:57    <DIR>          ..
2019/12/11  15:57                27 .dockerignore
2019/12/11  15:57                71 .gitignore
2019/12/11  15:57                23 .rspec
2019/12/11  15:57                80 .travis.yml
2019/12/11  15:57    <DIR>          .yardoc
2019/12/11  15:57    <DIR>          doc
2019/12/11  15:57    <DIR>          exe
2019/12/11  15:57                64 Gemfile
2019/12/11  15:57               786 Gemfile.lock
2019/12/11  15:57    <DIR>          lib
2019/12/11  15:57             1,108 LICENSE.txt
2019/12/11  15:57               996 my_help.gemspec
2019/12/11  15:57               438 Rakefile
2019/12/11  15:57            16,222 README.html
2019/12/11  15:57             4,269 README.org
2019/12/11  15:57                68 README.rdoc
2019/12/11  15:57             3,326 README_en.org
2019/12/11  15:57    <DIR>          spec
2019/12/11  15:57    <DIR>          test
              13 個のファイル              27,478 バイト
               8 個のディレクトリ  91,715,608,576 バイトの空き領域

------インストールしたmy_helpが見えた

C:\Users\lab\my_help>rake install:local
rake aborted!
LoadError: cannot load such file -- yard
C:/Users/lab/my_help/Rakefile:3:in `<top (required)>'
(See full trace by running task with --trace)
------謎のエラーが出た

**Comment by daddygongon** [comment]
解決しましたでしょうか？最新版(0.8.5)で少しwindows対応をいじってますので，それでもerrorが出るようでしたらおしらせください．その際に，rubyをどのようにinsatllされたかおしらせくださると助かります．

**Comment by XiaoHanQi** [comment]
前回の授業で最新版をインストールしましたけど，同じerrorが出ました．rubyが以下のURLを参考してインストールしました．
https://proengineer.internous.co.jp/content/columnfeature/12360#section102

**Comment by daddygongon** [comment]
yardは開発環境で必要とされるものです．実行環境には影響しませんので，そのままお使いください．
