### ISSUE TITLE
実行とgithub経由のinstallに必要なgem

### ISSUE THREAD

**Issue by MakoToyoda** [daddygongon/my_help#101]
OS:Win10 Pro
Shell:Windows Powershell
Editor:Sublime Text 3

my_help version を実行しようとしたときに"cannot load such file -- thor" エラーが出ました．
また，githubからcloneしてver0.8.2をinstallする際，rake install:local の実行時に"cannot load such file -- yard"エラーが出ました．

それぞれ gem install thor，gem install yardで足りないと言われたgemをinstallすることにより，いずれのエラーも解消しました

**Comment by daddygongon** [comment]
Windowsのpowershellですか．試して見ます．

**Comment by daddygongon** [comment]
thor, yardなどのdependentしているgemsも自動でinstallしてくれるはずです．再度，0.8.5をinstallしてください．

**Comment by MakoToyoda** [comment]
thor, yard, my_helpを一旦uninstallしてからgem install my_helpでmy_helpを再installしたところ，my_helpとthorがinstallされ，その後も正常に動作しました．
cloneしたファイルからのinstallは，直前にgit pullを行ってからrake install:localを実行しましたがyardを要求するエラーが吐かれ，installは行われませんでした．

**Comment by daddygongon** [comment]
ありがとうございます．git pullからのyardエラーは開発環境でのエラーです．実行環境には影響ありませんので，無視ください．
