### ISSUE TITLE
my_help install

### ISSUE THREAD

**Issue by megane-monkey** [daddygongon/my_help#102]
Windows10 Home, cmd, atom

インストール成功
ver 0.8.2(my_help), 2.6.5(ruby)

**Comment by megane-monkey** [comment]
my_help実行結果

Commands:
  my_help delete {help_name}    # delete HELP_NAME
  my_help edit {help_name}      # edit HELP_NAME
  my_help editor {editor_name}  # set editor
  my_help help [COMMAND]        # Describe available commands or one specific...
  my_help list                  # list helps, specific HELP, or item
  my_help new {help_name}       # make new HELP_NAME
  my_help search {find_char}    # search FIND_CHAR
  my_help setup                 # set up the test database
  my_help version               # show version

my_help version実行結果
#<Errno::ENOENT: No such file or directory @ rb_sysopen - C:/Users/藤田/.my_help/.my_help_conf.yml>
0.8.2

バージョン調べるときに、エラーメッセージとバージョンが両方出力される

**Comment by megane-monkey** [comment]
バージョンを「0.8.2」から「0.8.3」にアップグレード
出力結果は以下の通り

C:\Users\藤田\my_help>my_help
Commands:
  my_help delete HELP             # delete HELP
  my_help edit HELP               # edit HELP
  my_help help [COMMAND]          # Describe available commands or one specif...
  my_help list [HELP] [ITEM]      # list all helps, specific HELP, or ITEM
  my_help new HELP                # make new HELP
  my_help set_editor EDITOR_NAME  # set editor to EDITOR_NAME
  my_help setup                   # set up the test database
  my_help version                 # show version

C:\Users\藤田\my_help>my_help version
0.8.3

0.8.2の時に発生したエラーメッセージが消えた
serchがコマンドの中からなくなり、set_editorがコマンドの中に追加された

**Comment by megane-monkey** [comment]
エラーメッセージあり

C:\Users\藤田\my_help>my_help list
Traceback (most recent call last):
        18: from C:/Ruby26-x64/bin/my_help:23:in `<main>'
        17: from C:/Ruby26-x64/bin/my_help:23:in `load'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/exe/my_help:70:in `<top (required)>'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/exe/my_help:17:in `list'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/lib/my_help/my_help_controll.rb:56:in `list_all'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/lib/my_help/my_help_controll.rb:56:in `each'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/lib/my_help/my_help_controll.rb:59:in `block in list_all'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/lib/my_help/my_help_controll.rb:193:in `auto_load'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/lib/my_help/my_help_controll.rb:193:in `new'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/lib/my_help/org2yml.rb:13:in `initialize'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/lib/my_help/org2yml.rb:39:in `org_to_yaml'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/lib/my_help/org2yml.rb:39:in `each'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/lib/my_help/org2yml.rb:40:in `block in org_to_yaml'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/lib/my_help/org2yml.rb:40:in `match'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/lib/my_help/org2yml.rb:40:in `match': invalid byte sequence in Windows-31J (ArgumentError)

**Comment by daddygongon** [comment]
このエラーはなんだろう．0.8.5にversionをあげて試して見てください．

**Comment by daddygongon** [comment]
エラー確認しました．もう少しいじってみます

**Comment by daddygongon** [comment]
改良しました．
```
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.3/lib/my_help/org2yml.rb:40:in `match': invalid byte sequence in Windows-31J (ArgumentError)
```
の原因は，windows10上のpowerwhellのEncodingのdefaultがWindows-31Jだからです．
これにstring.matchをかけると
```
incompatible character encodings: Windows-31J and UTF-8 (Encoding::CompatiblitiyError)
```
がでます．

解決策は， powershellのrubyに
```
set RUBYOPT=-EUTF-8
set RUBYOPT=--encoding=UTF-8
```
などとすれば良さそうであるが，これでは修正できなかった．

そこで，codeを書き換えた．
[[https://ruby-doc.org/core-2.2.0/Encoding.html]]
にある通り，force_encodingすると良さそうである．
``` ruby
      if m = line.match(/^\* (.+)/)
=>
m=line.force_encoding(Encoding::UTF_8).match(/^\* (.+)/u)
if m
```
とした．これは，lineのEncodingをUTF-8に強制的に書き換えて，
それをmatch(/.../u)でutfでmatchingをかけるという手法である．
[[https://ruby-doc.org/core-2.2.0/Regexp.html#class-Regexp-label-Encoding]]
