### ISSUE TITLE
my_help list emacs file

### ISSUE THREAD

**Issue by resedet** [daddygongon/my_help#104]
# 環境

$ uname -a
Linux resedet 4.9.189 #1 SMP Mon Oct 7 10:55:57 JST 2019 x86_64GNU/Linux

$ cat /etc/debian_version
9.9

$ emacs --version
GNU Emacs 25.1.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

$ ruby -v
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

$ gem -v
2.5.2.1

# gem からインストールしたとき

my_help list emacs -f では正しく出力結果が表示されるが、
my_help list emacs file では途中までは表示されるが、エラーが起きる。

以下を実行した。

$ sudo gem install my_help
$ sudo gem install thor

$ my_help help delete
>Usage:
>  my_help delete {help_name}
>
>delete HELP_NAME

$ my_help new new_help
>/var/lib/gems/2.3.0/gems/my_help-0.8.0/lib/my_help/my_help_controll.rb:14:in `set_help_dir_if_not_exists': uninitialized constant MyHelp::Control::FileUtils (NameError)
>Did you mean?  FileTest
>        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/lib/my_help/my_help_controll.rb:9:in `initialize'
>        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:28:in `new'
>        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:28:in `new'
>        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
>        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
>        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
>        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
>        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:52:in `<top (required)>'
>        from /usr/local/bin/my_help:22:in `load'
>        from /usr/local/bin/my_help:22:in `<main>'

my_help_controll.rb が以前の version? になっている。
以下を my_help_controll.rb に追加したら動いた。

>require 'fileutils'
>require 'yaml'

$ my_help list
> List all helps
>       org: - emacs org-modeのhelp
>  new_help: - ヘルプのサンプル雛形
>     emacs: - Emacs key bind
>      todo: - my todo

$ my_help list emacs -f
>- Emacs key bind
>- 
>special key command
>-   c-f, While pressing the control key, press 'f'
>-   M-f, After pressing Esc key, press 'f'
>-   c-g, Operation interruption 
>-   c-x u, Undo operation(Undo)
>-----
>file operation file
>- c-x c-f, Find file, Find file
>- c-x c-s, Save file, Save file
>- c-x c-w, Write file NAME, Write a file with another name
>
$ my_help list emacs file
>- Emacs key bind
>- 
>special key command
>-   c-f, While pressing the control key, press 'f'
>-   M-f, After pressing Esc key, press 'f'
>-   c-g, Operation interruption 
>-   c-x u, Undo operation(Undo)
>-----
>/var/lib/gems/2.3.0/gems/my_help-0.8.0/lib/my_help/my_help_controll.rb:33:in `show_item': undefined method `[]' for nil:NilClass (NoMethodError)
>        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:16:in `list'
>        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
>        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
>        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
>        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
>        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:52:in `<top (required)>'
>        from /usr/local/bin/my_help:22:in `load'
>        from /usr/local/bin/my_help:22:in `<main>'

my_help list emacs -f では正しく出力結果が表示されるが、
my_help list emacs file では途中までは表示されるが、エラーが起きる。

# git clone してきたとき

$ ls                                                             [/var/tmp/my_help]
>doc/  Gemfile       lib/         my_help.gemspec  README_en.org  README.org   spec/
>exe/  Gemfile.lock  LICENSE.txt  Rakefile         README.html    README.rdoc  test/

$ rake install:local
>rake aborted!
>LoadError: cannot load such file -- bundler/gem_tasks
>/home/ryota/doc/lab/multi-scale/my_help/Rakefile:1:in `<top (required)>'
>(See full trace by running task with --trace)

$ rake install:local --trace
>rake aborted!
>LoadError: cannot load such file -- bundler/gem_tasks
>/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>/home/ryota/doc/lab/multi-scale/my_help/Rakefile:1:in `<top (required)>'
>/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load'
>/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load_rakefile'
>/usr/lib/ruby/vendor_ruby/rake/application.rb:689:in `raw_load_rakefile'
>/usr/lib/ruby/vendor_ruby/rake/application.rb:94:in `block in load_rakefile'
>/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
>/usr/lib/ruby/vendor_ruby/rake/application.rb:93:in `load_rakefile'
>/usr/lib/ruby/vendor_ruby/rake/application.rb:77:in `block in run'
>/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
>/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
>/usr/bin/rake:27:in `<main>'

必要な bundler がない。
bundler を入れたら動く?

**Comment by resedet** [comment]
$ sudo gem install my_help
で、my_help を再インストールした。
$ my_help version
0.8.3

エディタを設定する時にエラーは起きなかった。
＄ my_help set_editor emacs

**Comment by daddygongon** [comment]
0.8.3はいいんですよ．
