### ISSUE TITLE
gem install my_help

### ISSUE THREAD

**Issue by masa1290** [daddygongon/my_help#105]
**環境**
OS: macOS 10.14.5
ruby: 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
gem: 2.5.2.3

**コマンド**
`gem install my_help`

**結果**
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.

**考察**
システムのgemを使っているため、パーミッションが無い？

**Comment by daddygongon** [comment]
sudoつけてgem installを最実行してください．
