### ISSUE TITLE
my_help report

### ISSUE THREAD

**Issue by hokamon** [daddygongon/my_help#108]
* 環境
OS: Linux Debian 9.0
Shell: zsh
Editor: emacs

* 0.8.0
gem install で
- my_help
- thor
をダウンロードした後、
コマンドを打ったところ以下のエラーが発生
ryuichiro@StudioOne[0]: my_help list memo.org                                                                      [~]
/var/lib/gems/2.3.0/gems/my_help-0.8.0/lib/my_help/my_help_controll.rb:14:in `set_help_dir_if_not_exists': uninitialized constant MyHelp::Control::FileUtils (NameError)
Did you mean?  FileTest
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/lib/my_help/my_help_controll.rb:9:in `initialize'
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:28:in `new'
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:28:in `new'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:52:in `<top (required)>'
        from /usr/local/bin/my_help:22:in `load'
        from /usr/local/bin/my_help:22:in `<main>'

ryuichiro@StudioOne[0]: my_help new test                                                                           [~]
/var/lib/gems/2.3.0/gems/my_help-0.8.0/lib/my_help/my_help_controll.rb:14:in `set_help_dir_if_not_exists': uninitialized constant MyHelp::Control::FileUtils (NameError)
Did you mean?  FileTest
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/lib/my_help/my_help_controll.rb:9:in `initialize'
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:8:in `new'
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:8:in `list'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:52:in `<top (required)>'
        from /usr/local/bin/my_help:22:in `load'
        from /usr/local/bin/my_help:22:in `<main>'

予想: 必要なディレクトリがない？

* 0.8.2
rake を行うとエラー
---------------------- ここから ---------------------- 
ryuichiro@StudioOne[0]: rake                                   
rake aborted!
LoadError: cannot load such file -- bundler/gem_tasks
/home/ryuichiro/my_help/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)
--------------------- ここまで ---------------------- 

エラーメッセージから bundler が足りなさそうなのでインストール
--------------------- ここから ---------------------- 
ryuichiro@StudioOne[0]: sudo gem install bundler -r -p http://proxy.ksc.kwansei.ac.jp:8080                 [~/my_help]
[sudo] password for ryuichiro:                  
Fetching: bundler-2.0.2.gem (100%)
Successfully installed bundler-2.0.2
Parsing documentation for bundler-2.0.2
Installing ri documentation for bundler-2.0.2
Done installing documentation for bundler after 3 seconds
1 gem installed
--------------------- ここまで ---------------------- 

もう一度 rake コマンドを行うが、再びエラー
--------------------- ここから ---------------------- 
ryuichiro@StudioOne[0]: rake                                                                               [~/my_help]
rake aborted!
LoadError: cannot load such file -- yard
/home/ryuichiro/my_help/Rakefile:3:in `<top (required)>'
(See full trace by running task with --trace)
--------------------- ここまで ---------------------- 

エラーメッセージから yard コマンドが 足りないようなのでインストール
--------------------- ここから ---------------------- 
ryuichiro@StudioOne[0]: sudo gem install yard -r -p http://proxy.ksc.kwansei.ac.jp:8080                    [~/my_help]
Fetching: yard-0.9.20.gem (100%)
--------------------------------------------------------------------------------
As of YARD v0.9.2:

RubyGems "--document=yri,yard" hooks are now supported. You can auto-configure
YARD to automatically build the yri index for installed gems by typing:

    $ yard config --gem-install-yri

See `yard config --help` for more information on RubyGems install hooks.

You can also add the following to your .gemspec to have YARD document your gem
on install:

    spec.metadata["yard.run"] = "yri" # use "yard" to build full HTML docs.

--------------------------------------------------------------------------------
Successfully installed yard-0.9.20
Parsing documentation for yard-0.9.20
Installing ri documentation for yard-0.9.20
Done installing documentation for yard after 3 seconds
1 gem installed
--------------------- ここまで ---------------------- 

再び rake コマンドを打ち込む
ryuichiro@StudioOne[0]: rake  

 エラーも特に出ずに動いた

**Comment by daddygongon** [comment]
ご苦労をおかけします．bundlerを使えば，dependencyは通常の設定では自動でinstallされるはずです．試して見てください．
