### ISSUE TITLE
info

### ISSUE THREAD

**Issue by uzanyan** [daddygongon/my_help#109]
インストール：成功
C:\Users\Y.Kimura\test1\grad_lecture_19\members\kimura>gem install -p http://proxy.ksc.kwansei.ac.jp:8080 my_help
Fetching my_help-0.8.3.gem
Fetching thor-1.0.1.gem
Successfully installed thor-1.0.1
Successfully installed my_help-0.8.3
Parsing documentation for thor-1.0.1
Installing ri documentation for thor-1.0.1
Parsing documentation for my_help-0.8.3
Installing ri documentation for my_help-0.8.3
Done installing documentation for thor, my_help after 5 seconds
2 gems installed

**Comment by daddygongon** [comment]
proxyの設定がいらなくなりました．
