### ISSUE TITLE
my_help install

### ISSUE THREAD

**Issue by koshipakaman** [daddygongon/my_help#110]
OS:Ubuntu 18.04
Shell: zsh
Editor: neovim

インストール、動作ともに成功した

[koshipakaman ~]% sudo gem install -p http://proxy.kwansei.ac.jp:8080 my_help
Fetching: my_help-0.8.3.gem (100%)
Successfully installed my_help-0.8.3
Parsing documentation for my_help-0.8.3
Installing ri documentation for my_help-0.8.3
Done installing documentation for my_help after 0 seconds
1 gem installed

**Comment by daddygongon** [comment]
proxyの設定がなくなりました．
