### ISSUE TITLE
アイテム名の頭文字に重複が存在すると、アイテム名を指定してヘルプを表示できない

### ISSUE THREAD

**Issue by masa1290** [daddygongon/my_help#112]
OS: mac 10.14.5
ruby: 2.7.0p0
gem: 3.1.2

例えば、以下のようにnew_help.orgを作成します：
```
* license
 　- cc by Shigeto R. Nishitani, 2016
* head
　- 新しいヘルプ
* item1_example
　- item1
* item2_example
　- item2
```

`my_help list new_help`を実行すると、"item1_example"に対応するアイテム名は"-i"と設定されますが、"item2_example"に対応するアイテム名は設定されません：
```
- 新しいヘルプ
     , head           : head
     , license        : license
   -i, item1_example  : item1_example
     , item2_example  : item2_example
```

この状態で`my_help list new_help -i`を実行すると、"item1_example"のみに関するヘルプが表示されます：
```
- 新しいヘルプ
-----
item1_example
- item1
```

orgファイルにある見出しの頭文字がITEM名になるので、このような挙動になるのだと思います。頭文字が同じである場合は、番号をつけるか、自分でITEM名を指定できるようなオプションが欲しいです。よろしくお願いします。

**Comment by daddygongon** [comment]
順番を入れ替えてください．short optionで出したい項目をeditorで上の方におけばそちらが参照されます．番号を付与するというのはいいアイデアなんで，検討してみます．ご提案ありがとうございます．
