### ISSUE TITLE
linux debian への新規インストール

### ISSUE THREAD

**Issue by natsuko-k** [daddygongon/my_help#27]
これからインストールさせてもらいます。

環境は、linux debian (version 7.11) です。
よろしくお願いします。

**Comment by daddygongon** [comment]
よろしくお願いします．

**Comment by OyagiToshiharu** [comment]
yagiです．よろしくお願いいたします．

**Comment by natsuko-k** [comment]
こんにちは、Natsuko です。

$ bundle exec exe/my_help を実行したところ、下記のエラーが出ました。
-------------- ここから --------------
Could not find gem 'yard' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
-------------- ここまで --------------

対処法がわかれば、教えていただけませんか?

**Comment by daddygongon** [comment]
> bundle update
を試してみてください．proxy配下ではproxy設定が必要かもしれません．

**Comment by natsuko-k** [comment]
実行できました。
ありがとうございました。

**Comment by natsuko-k** [comment]
英語バージョンはありますか?
あれば英語の方が嬉しいです。

**Comment by daddygongon** [comment]
承りました．配下に作らせます．設定されているのは，ENV[LANG]ですか？

**Comment by daddygongon** [comment]
英語版のemacs_helpなどをつくってください．

* emacs_help_e.ymlなどとして英語版とその他を区別しましょう．
* 英語版がdefaultなら_jをつけましょう．
* 拡張子(_e, _j)が無いときはそのままの表示としましょう．

**Comment by OyagiToshiharu** [comment]
英語版のemacs_helpの作成，承りました．
