### ISSUE TITLE
takemotoへの新規インストール

### ISSUE THREAD

**Issue by takemotoatsushi** [daddygongon/my_help#28]
my_helpをインストールさせていただきます。

環境はUbuntu16.04です。

よろしくお願いいたします。

**Comment by OyagiToshiharu** [comment]
よろしくお願いします．

**Comment by takemotoatsushi** [comment]
インストールが無事完了いたしました．
生じたエラーは
------------------------------------------------------------------------------------
Could not find gem 'yard' in any of the gem sources listed in your Gemfile.
Run bundle install to install missing gems
------------------------------------------------------------------------------------
でしたが，natsuko-kさんのIsuuesを参考に解決することができました．

インストールにおけるバグがほとんどなく，みつけることができなかったので，
苦し紛れにREADME.ipynbにおける誤り箇所をご報告させていただきます．

userの独自helpの達成方法の3行上
~さらにlocalへのinstallにはsudoがいるかもしれませ．

ご訂正のほど，よろしくお願いいたします．
