### ISSUE TITLE
Ubuntuへの新規インストール

### ISSUE THREAD

**Issue by taishifujiwara1221** [daddygongon/my_help#29]
インストールさせて頂きます．
環境は， Ubuntu16.04 日本語版です．

よろしくお願いします．

**Comment by OyagiToshiharu** [comment]
よろしくお願いします．

**Comment by taishifujiwara1221** [comment]
インストール中にnatsukoさんと同様のエラーが出ましたが，
同様の解決法を試したところ問題なくインストール出来ました．

ひとつ気になったところが，
bundle exec exe/my_help を実行した時の結果が
readme では

Usage: my_help [options]
    -v, --version                    show program Version.
    -l, --list                       個別(specific)ヘルプのList表示.
    -e, --edit NAME                  NAME(例：test_help)をEdit編集.
    -i, --init NAME                  NAME(例：test_help)のtemplateを作成.
    -m, --make                       make executables for all helps.
    -c, --clean                      clean up exe dir.
        --install_local              install local after edit helps
        --delete NAME                delete NAME help

と日本語を含んでいるのに，
実際に実行したところ

bundle exec exe/my_help
Usage: my_help [options]
    -v, --version                    show program Version.
    -l, --list                       list specific helps
    -e, --edit NAME                  edit NAME help(eg test_help)
    -i, --init NAME                  initialize NAME help(eg test_help)
    -m, --make                       make executables for all helps
    -c, --clean                      clean up exe dir.
        --install_local              install local after edit helps
        --delete NAME                delete NAME help

と英語のみになっており
環境の違いなのか，というところが少し気になりました．

**Comment by daddygongon** [comment]
はい．その通りだとおもいます．まだ気になるようでしたら再度問い合わせをお願いします．
できれば，env の出力結果，あるいはenv | grep LANGの結果をお知らせください．
