### ISSUE TITLE
異なる環境へのインストール

### ISSUE THREAD

**Issue by daddygongon** [daddygongon/my_help#82]
# 目的
my_helpを多様な環境で動作するように改良する．

# 現状
mac + emacs でしか動かせてない．

# 方針
- ~/.my_Help/.configにeditorを規定してそれで動くようにする
- 環境に従って，system callを変える

# 大学院生への課題
- 環境(os, shell, editor)を報告
- 起動したらok
- 不具合(error)を報告
- 工夫して起動したらそれを報告

**Comment by syasin-5d** [comment]
> ~/.my_Help/.configにeditorを規定してそれで動くようにする

環境変数 EDITOR を読みにいくのはいかがでしょうか。

**Comment by daddygongon** [comment]
ありがとうございます．0.8.6で変更しました．
EDITORが設定された状態でinstallするとmy_helpで設定されます．
あとでEDITORを変更しても反映されません．
これは，my_helpとEDITORを区別して使っている可能性があるからです．
後で変更したい場合は，明示的にmy_helpでset_editortしてください
