### ISSUE TITLE
my_help install (editできない)

### ISSUE THREAD

**Issue by mizunomi32** [daddygongon/my_help#83]
## 環境
os : macOS 10.15.1
ruby : 2.6.5
gem : 3.0.3
インストール可否 : 成功

## Bug
``my_help edit `` でのファイル編集ができない
![スクリーンショット 2019-12-11 15 40 27](https://user-images.githubusercontent.com/13363322/70597785-93adc880-1c2c-11ea-86ab-57bc875aa7aa.png)

**Comment by mizunomi32** [comment]
環境変数側でEditorの指定しているのが影響しているかもしれません

**Comment by mizunomi32** [comment]
Zsh, neovimを使用してます
環境変数のEDITORにnvimを設定している影響かもしれません

**Comment by mizunomi32** [comment]
v.0.8.2では問題なく動作しました

**Comment by daddygongon** [comment]
早速ありがとうございます．良かったです．
