### ISSUE TITLE
my_help search

### ISSUE THREAD

**Issue by whale8** [daddygongon/my_help#84]
**環境**

OS: macOS 10.14.6
ruby: 2.6.0
gem: 3.0.1

install 成功

**Bug**
```my_help search``` が動かない。
```
undefined method `search_help' for #<MyHelp::Control:0x00007fbd9a8f95f8> (NoMethodError)
```

**Comment by whale8** [comment]
```my_help search "hoge"```や```my_help search hoge```も試したが同様。

**Comment by whale8** [comment]
fishを使用。

**Comment by whale8** [comment]
ver.0.8.2では動きました。

**Comment by daddygongon** [comment]
search 実装してません．ごめんなさい．
