### ISSUE TITLE
"Could not find command"時の表示バグ

### ISSUE THREAD

**Issue by Phantasmanoria** [daddygongon/my_help#85]
## 環境
- Ubuntu 18.04 LTS
- zsh
- tmux
- ruby 2.5.3
- rbenv
- emacs 25.2.2

## 問題
存在しないコマンドを入れた時に出てくる"Could not find **command"のコマンド名の表示の一部がおかしくなる(具体的には先頭に半角ハイフンを入れた時)

## 例
%my_help aaaa
my_help aaaa
Could not find command "aaaa".
%my_help aa-aa 
my_help aa-aa
Could not find command "aa-aa".
%my_help -aaaa 
my_help -aaaa
Could not find command "_aaaa".

**Comment by daddygongon** [comment]
これはthorの仕様なんで許してください．
-はshort optionを期待するんで，それが対応していないcommand
だというのがthorの方から出ています．
ご容赦ください．

**Comment by daddygongon** [comment]
my_help set_editor 'emacs -nw'は動いた？
