### ISSUE TITLE
my_help install

### ISSUE THREAD

**Issue by rukurei0173** [daddygongon/my_help#86]
Mac(10.14.6), zsh

my_help list や my_help emacsはできるが, 
my_help versionだけできない
-my_help version
Could not find command "version".

gem install my_helpを行うと
0.8.1でなく0.8.0が入る
-gem install my_help
Successfully installed my_help-0.8.0
1 gem installed

emacsは開くがatom, vimは開かない

-my_help edit emacs
"/Users/reina/.my_help/emacs.org"

-my_help edit vim
"/Users/reina/.my_help/vim.org"
file /Users/reina/.my_help/vim.org does not exits in /Users/reina/.my_help.
init vim first.

-my_help edit atom
"/Users/reina/.my_help/atom.org"
file /Users/reina/.my_help/atom.org does not exits in /Users/reina/.my_help.
init atom first.

**Comment by daddygongon** [comment]
0.8.2を再インストールしてください．修正済みです．
ありがとうございます．atomで動いたらここへ報告してください．

**Comment by daddygongon** [comment]
atomへの変更は，
my_help set_editor atom
です．
