### ISSUE TITLE
my_help install

### ISSUE THREAD

**Issue by Yuka-Azuma** [daddygongon/my_help#87]
ubuntu (18.04.3) / zsh 

$gem install my_help                                                                                                                                                                                     
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.

でインストール出来なかった。

$sudo gem install my_help                                                                                                                                                                                
Fetching: gli-2.17.1.gem (100%)
Successfully installed gli-2.17.1
Fetching: my_help-0.8.0.gem (100%)
Successfully installed my_help-0.8.0
Parsing documentation for gli-2.17.1
Installing ri documentation for gli-2.17.1
Parsing documentation for my_help-0.8.0
Installing ri documentation for my_help-0.8.0
Done installing documentation for gli, my_help after 0 seconds
2 gems installed

インストールされたが 0.8.0 がインストールされた.

$ my_help list                                                                                                                                                                                            
Traceback (most recent call last):
	4: from /usr/local/bin/my_help:23:in `<main>'
	3: from /usr/local/bin/my_help:23:in `load'
	2: from /var/lib/gems/2.5.0/gems/my_help-0.8.0/exe/my_help:2:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- thor (LoadError)

どのコマンドを入力してもエラーが出る.

$sudo gem install thor                                                                                                                                                                                   
Fetching: thor-0.20.3.gem (100%)
Successfully installed thor-0.20.3
Parsing documentation for thor-0.20.3
Installing ri documentation for thor-0.20.3
Done installing documentation for thor after 0 seconds
1 gem installed

thor をインストールした

$my_help list                                                                                                                                                                                            
List all helps
     emacs: - Emacs key bind
      todo: - my todo
       org: - emacs org-modeのhelp

正しく表示が出来た

$my_help version                                                                                                                                                                                         
Could not find command "version".

$my_help edit atom                                                                                                                                                                                       
"/home/azu/.my_help/atom.org"
file /home/azu/.my_help/atom.org does not exits in /home/azu/.my_help.
init atom first.

エラーが出る.

**Comment by daddygongon** [comment]
my_help editor atom
editではなく，editorでeditorを指定してください．
my_help edit atom
はatom というhelpを探します．
その場合は，
my_help init atom
としてatomというhelpをまずは作ってください．
これは，よくやる間違いなので，manualに入れます．
