### ISSUE TITLE
delete時にそのままEnterを入力しても削除が実行されない

### ISSUE THREAD

**Issue by Phantasmanoria** [daddygongon/my_help#88]
## 環境
- Ubuntu 18.04 LTS
- zsh
- tmux
- ruby 2.5.3
- rbenv
- emacs 25.2.2

## 問題
my_help delete実行時にそのままEnterを入力しても削除が行われない
[Ynq]の選択肢のうち,　yが大文字なので未入力の場合はY(削除)が実行されるべきと思われる

## 例
%my_help delete test
my_help delete test
Are you sure to delete /home/user/.my_help/test.org?[Ynq] 
%my_help delete test
my_help delete test
Are you sure to delete /home/user/.my_help/test.org?[Ynq] y
%my_help delete test
my_help delete test
Are you sure to delete /home/user/.my_help/test.org?[Ynq] Y
rm /home/user/.my_help/test.org

**Comment by daddygongon** [comment]
そのように変更します．
