### ISSUE TITLE
my_help add {help name}

### ISSUE THREAD

**Issue by kaz9641** [daddygongon/my_help#90]
環境
-------------

os :  debian 9
カーネル：Linux wei 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
gem : 2.5.2.1
インストール可否 : 成功

バグ
------

my_help new {help_name} を実行すると、エラーが出る

% my_help new kaz
/var/lib/gems/2.3.0/gems/my_help-0.8.0/lib/my_help/my_help_controll.rb:14:in `set_help_dir_if_not_exists': uninitialized constant MyHelp::Control::FileUtils (NameError)
Did you mean?  FileTest
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/lib/my_help/my_help_controll.rb:9:in `initialize'
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:28:in `new'
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:28:in `new'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:52:in `<top (required)>'
        from /usr/local/bin/my_help:22:in `load'
        from /usr/local/bin/my_help:22:in `<main>'

**Comment by daddygongon** [comment]
お使いのmy_helpは0.8.0です．
gem install my_help
で最新版(0.8.5)を入れてください．
