### ISSUE TITLE
my_help install

### ISSUE THREAD

**Issue by y-kotakehara** [daddygongon/my_help#92]
os:Windows Subsystem for Linux Ubuntu 18.04 LTS

gem install my_help だとインストール失敗
Fetching: gli-2.17.1.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.

sudo gem install my_help だとインストール成功
Fetching: gli-2.17.1.gem (100%)
Successfully installed gli-2.17.1
Fetching: my_help-0.8.0.gem (100%)
Successfully installed my_help-0.8.0
Parsing documentation for gli-2.17.1
Installing ri documentation for gli-2.17.1
Parsing documentation for my_help-0.8.0
Installing ri documentation for my_help-0.8.0
Done installing documentation for gli, my_help after 1 seconds
2 gems installed

my_help インストールに成功した?だがしかし動かない
Traceback (most recent call last):
        4: from /usr/local/bin/my_help:23:in `<main>'
        3: from /usr/local/bin/my_help:23:in `load'
        2: from /var/lib/gems/2.5.0/gems/my_help-0.8.0/exe/my_help:2:in `<top (required)>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- thor (LoadError)

sudo gem install thor thorをインストールしてみた
Fetching: thor-0.20.3.gem (100%)
Successfully installed thor-0.20.3
Parsing documentation for thor-0.20.3
Installing ri documentation for thor-0.20.3
Done installing documentation for thor after 1 seconds
1 gem installed

my_help thorをインストール後動くようになった
Commands:
/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/shell/basic.rb:399: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
  my_help delete {help_name}       # delete HELP_NAME
  my_help edit {help_name}         # edit HELP_NAME
  my_help help [COMMAND]           # Describe available commands or one specific command
  my_help list                     # list all helps, specific HELP, or item
  my_help new {help_name}          # make new HELP_NAME
  my_help search {find_char}       # search FIND_CHAR
  my_help tomo_upload {help_name}  # tomo_upload HELP_NAME

**Comment by daddygongon** [comment]
使ってやってください．
