### ISSUE TITLE
my_help install

### ISSUE THREAD

**Issue by Yu-shun** [daddygongon/my_help#94]
windows 10 pro, cmd, atom

>export http_proxy=http://proxy.kwansei.ac.jp:8080
'export' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
cmdはexportではなくset
>set http_proxy=http://proxy.kwansei.ac.jp:8080

my_helpとthorのインストール
>gem install my_help
>gem install thor

version
my_help 0.8.0
ruby 2.6.4

rake エラー吐く
>rake install:local
rake aborted!
LoadError: cannot load such file -- yard
C:/Users/lab/Desktop/my_help/Rakefile:3:in `<top (required)>'
(See full trace by running task with --trace)

gem install rakeしたけど無理でした

**Comment by daddygongon** [comment]
proxyを外して最新版を入れてください．動くはずです．
