### ISSUE TITLE
my_help install

### ISSUE THREAD

**Issue by morimorimorino** [daddygongon/my_help#95]
OS:macOS Catalina(10.15.1)
shell:fish
インストール可否：成功
実行可否：不可

インストールはできたが、バージョン確認する際にエラーが発生してしまう。
以下にそれまでの手順を記す。

yu-ma@dml1x07 ~/g/g/m/morino> my_help version
Traceback (most recent call last):
	4: from /usr/local/bin/my_help:23:in `<main>'
	3: from /usr/local/bin/my_help:23:in `load'
	2: from /Library/Ruby/Gems/2.6.0/gems/my_help-0.8.0/exe/my_help:2:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- thor (LoadError)

↓

sudo gem install thor -p http://proxy.kwansei.ac.jp:8080

↓

yu-ma@dml1x07 ~/g/g/m/morino> my_help version
Could not find command "version".

↓

git clone git@github.com:daddygongon/my_help.git

↓

yu-ma@dml1x07 ~/g/g/m/m/my_help> rake install:local
rake aborted!
LoadError: cannot load such file -- yard
/Users/yu-ma/github/grad_lecture_19/members/morino/my_help/Rakefile:3:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

↓

sudo gem install yard -p http://proxy.kwansei.ac.jp:8080

↓

yu-ma@dml1x07 ~/g/g/m/m/my_help> rake install:local
my_help 0.8.2 built to pkg/my_help-0.8.2.gem.
rake aborted!
Couldn't install gem, run `gem install /Users/yu-ma/github/grad_lecture_19/members/morino/my_help/pkg/my_help-0.8.2.gem' for more detailed output
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => install:local
(See full trace by running task with --trace)

↓

sudo gem install /Users/yu-ma/github/grad_lecture_19/members/morino/my_help/pkg/my_help-0.8.2.gem -p http://proxy.kwansei.ac.jp:8080

↓

yu-ma@dml1x07 ~/g/g/m/m/my_help> my_help version
Traceback (most recent call last):
	18: from /usr/local/bin/my_help:23:in `<main>'
	17: from /usr/local/bin/my_help:23:in `load'
	16: from /Library/Ruby/Gems/2.6.0/gems/my_help-0.8.2/exe/my_help:70:in `<top (required)>'
	15: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	14: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	13: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	12: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	11: from /Library/Ruby/Gems/2.6.0/gems/my_help-0.8.2/exe/my_help:35:in `version'
	10: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	 9: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 8: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 7: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/my_help-0.8.2/exe/my_help:8:in `setup'
	 5: from /Library/Ruby/Gems/2.6.0/gems/my_help-0.8.2/exe/my_help:8:in `new'
	 4: from /Library/Ruby/Gems/2.6.0/gems/my_help-0.8.2/lib/my_help/my_help_controll.rb:17:in `initialize'
	 3: from /Library/Ruby/Gems/2.6.0/gems/my_help-0.8.2/lib/my_help/my_help_controll.rb:34:in `load_conf'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:577:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:577:in `initialize': No such file or directory @ rb_sysopen - /Users/yu-ma/.my_help/.my_help_conf.yml (Errno::ENOENT)

**Comment by daddygongon** [comment]
thorがないというエラーですね．最新版(0.8.5))を入れてください．
