### ISSUE TITLE
my_help

### ISSUE THREAD

**Issue by terapone** [daddygongon/my_help#96]
os: windows 10 Pro
shell: git bash
インストール可否: 成功
実行可否: 不可

インストールできましたが，version確認時にエラーが出ます．

terap@DESKTOP-R6FHGQA MINGW64 ~/my_help (master)
$ my_help version
C:/Ruby26-x64/lib/ruby/2.6.0/psych.rb:577:in `initialize': No such file or directory @ rb_sysopen - C:\Users\terap/.my_help/.my_help_conf.yml (Errno::ENOENT)
        from C:/Ruby26-x64/lib/ruby/2.6.0/psych.rb:577:in `open'
        from C:/Ruby26-x64/lib/ruby/2.6.0/psych.rb:577:in `load_file'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.2/lib/my_help/my_help_controll.rb:34:in `load_conf'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.2/lib/my_help/my_help_controll.rb:17:in `initialize'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.2/exe/my_help:8:in `new'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.2/exe/my_help:8:in `setup'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.2/exe/my_help:35:in `version'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/my_help-0.8.2/exe/my_help:70:in `<top (required)>'
        from C:/Ruby26-x64/bin/my_help:23:in `load'
        from C:/Ruby26-x64/bin/my_help:23:in `<main>'

**Comment by daddygongon** [comment]
最新版(0.8.5)を入れ直してください．
