### ISSUE TITLE
作成した"*.org"を直接編集することが出来ない

### ISSUE THREAD

**Issue by Phantasmanoria** [daddygongon/my_help#97]
## 環境
- Ubuntu 18.04 LTS
- zsh
- tmux
- ruby 2.5.3
- rbenv
- emacs 25.2.2

## 問題
「my_help new " * "」でorgを作成して同じく「my_help edit " * "」で編集しようとすると直接表示が行われない(.my_help内の全てのorgが候補になっていると思われる)

## 例
%my_help new " * "
my_help new " * "
"/home/user/.my_help/*.org"
"/home/user/.anyenv/envs/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/my_help-0.8.0/lib/templates/help_template.org"
cp /home/user/.anyenv/envs/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/my_help-0.8.0/lib/templates/help_template.org /home/user/.my_help/*.org
%my_help edit " * "
my_help edit "*"
"/home/user/.my_help/*.org"

**Comment by daddygongon** [comment]
これはshellの仕様です．他のhelpを作ってください．
