### ISSUE TITLE
my_help install

### ISSUE THREAD

**Issue by a1i1m0i7** [daddygongon/my_help#98]
Windows 10 Pro，cygwin

setenv http_proxy http://proxy.kwansei.ac.jp:8080; setenv https_proxy http://proxy.kwansei.ac.jp:8080
を実行すると，
-bash: setenv: コマンドが見つかりません
となったので
export http_proxy=http://proxy.kwansei.ac.jp:8080  
を代わりにすると，my_helpをインストールできたが，
Successfully installed my_help-0.8.0
となり，0.8.0がインストールされた．

my_helpを実行したところ，
Commands:
      1 [main] ruby 11980 child_info_fork::abort: address space needed by 'transdb.so' (0x2770000) is already occupied...
とよく分からない文が出てきたが，その原因はrubyのバージョンが古いもの(ruby 1.9.3p327 (2012-11-10 revision 37606))だからと考えられる．

**Comment by daddygongon** [comment]
申し訳ないですが，ruby をあげてください．
