### ISSUE TITLE
UNIX 環境(debian) での挙動

### ISSUE THREAD

**Issue by ChutaMinamiguchi** [daddygongon/my_help#99]
環境
---------------------------------------------------------------------------------
- debian9.8
- zsh
- ruby 2.3.3

実行内容
-------------------------------------------------------------------------------------
$ sudo gem install my_help

$ my_help
Commands:
  my_help delete {help_name}       # delete HELP_NAME
  my_help edit {help_name}         # edit HELP_NAME
  my_help help [COMMAND]           # Describe available commands or one specific command
  my_help list                     # list all helps, specific HELP, or item
  my_help new {help_name}          # make new HELP_NAME
  my_help search {find_char}       # search FIND_CHAR
  my_help tomo_upload {help_name}  # tomo_upload HELP_NAME

$ my_help -v   
Could not find command "_v".

$ my_help list      
/var/lib/gems/2.3.0/gems/my_help-0.8.0/lib/my_help/my_help_controll.rb:14:in `set_help_dir_if_not_exists': uninitialized constant MyHelp::Control::FileUtils (NameError)
Did you mean?  FileTest
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/lib/my_help/my_help_controll.rb:9:in `initialize'
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:8:in `new'
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:8:in `list'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /var/lib/gems/2.3.0/gems/my_help-0.8.0/exe/my_help:52:in `<top (required)>'
        from /usr/local/bin/my_help:22:in `load'
        from /usr/local/bin/my_help:22:in `<main>'

考察
-----------------------------------------------------------------------
list を表示しようとすると、NameError？ がでる。10分奮闘したが、解決できなかった。

オプションを指定すると、not find command が表示される。← ？

**Comment by daddygongon** [comment]
my_helpを最新版(0.8,5)にあげてください．
